export const cars = [
    {
      id: 1,
      name: "Koeingsegg",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "sport",
      gasoline: 90,
      price:90.00,
      capacity:2,
      image: "../assets/images/Car-1.png",
    },
    {
      id: 2,
      name: "Nissan GT-R",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "sport",
      gasoline: 80,
      price:80.00,
      capacity:2,
      image: "../assets/images/car-2.png",
    },
    {
      id: 3,
      name: "Rolls-Roys",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "sedan",
      gasoline: 70,
      price:99.00,
      capacity:4,
      image: "../assets/images/Car-3.png",
    },
    {
      id: 4,
      name: "Nissan GT-R",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "sport",
      gasoline: 80,
      price:96.00,
      capacity:2,
      image: "../assets/images/car-2.png",
    },
    {
      id: 5,
      name: "All New Rush",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "suv",
      gasoline: 70,
      price:72.00,
      capacity:6,
      image: "../assets/images/Car-5.png",
    },
    {
      id: 6,
      name: "CR-V",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "suv",
      gasoline: 80,
      price:74.00,
      capacity:6,
      image: "../assets/images/Car-6.png",
    },
    {
      id: 7,
      name: "All New Terios",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "coupe",
      gasoline: 90,
      price:76.00,
      capacity:6,
      image: "../assets/images/Car-7.png",
    },
    {
      id: 8,
      name: "CR-V",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      carType: "suv",
      gasoline: 80,
      price:112.00,
      capacity:6,
      image: "../assets/images/Car-8.png",
    },
    {
        id: 9,
        name: "MG ZX Exclusice",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "hatchback",
        gasoline: 70,
        price:67.00,
        capacity:4,
        image: "../assets/images/Car-9.png",
      },
      {
        id: 10,
        name: "New MG ZS",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "suv",
        gasoline: 80,
        price:94.00,
        capacity:6,
        image: "../assets/images/Car-10.png",
      },
      {
        id: 11,
        name: "MG ZX Excite",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "hatchback",
        gasoline: 80,
        price:78.00,
        capacity:6,
        image: "../assets/images/Car-11.png",
      },
      {
        id: 12,
        name: "New MG ZS",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "hatchback",
        gasoline: 80,
        price:100.00,
        capacity:6,
        image: "../assets/images/Car-12.png",
      },
      {
        id: 13,
        name: "Koeingsegg",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "sport",
        gasoline: 90,
        price:90.00,
        capacity:2,
        image: "./assets/images/Car-1.png",
      },
      {
        id: 14,
        name: "Nissan GT-R",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "sport",
        gasoline: 80,
        price:80.00,
        capacity:2,
        image: "../assets/images/car-2.png",
      },
      {
        id: 15,
        name: "Rolls-Roys",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "sedan",
        gasoline: 70,
        price:99.00,
        capacity:4,
        image: "../assets/images/Car-3.png",
      },
      {
        id: 16,
        name: "Nissan GT-R",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "sport",
        gasoline: 80,
        price:96.00,
        capacity:2,
        image: "../assets/images/car-2.png",
      },
      {
        id: 17,
        name: "All New Rush",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "suv",
        gasoline: 70,
        price:72.00,
        capacity:6,
        image: "../assets/images/Car-5.png",
      },
      {
        id: 18,
        name: "CR-V",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "suv",
        gasoline: 80,
        price:74.00,
        capacity:6,
        image: "../assets/images/Car-6.png",
      },
      {
        id: 19,
        name: "All New Terios",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "sport",
        gasoline: 90,
        price:76.00,
        capacity:6,
        image: "../assets/images/Car-7.png",
      },
      {
        id: 20,
        name: "CR-V",
        description: [
          { support: "گارانتی مادام العمر" },
          { support: "ارسال رایگان" },
          { support: "اورجینال" },
        ],
        carType: "suv",
        gasoline: 80,
        price:112.00,
        capacity:6,
        image: "../assets/images/Car-8.png",
      },
      {
          id: 21,
          name: "MG ZX Exclusice",
          description: [
            { support: "گارانتی مادام العمر" },
            { support: "ارسال رایگان" },
            { support: "اورجینال" },
          ],
          carType: "hatchback",
          gasoline: 70,
          price:67.00,
          capacity:4,
          image: "../assets/images/Car-9.png",
        },
        {
          id: 22,
          name: "New MG ZS",
          description: [
            { support: "گارانتی مادام العمر" },
            { support: "ارسال رایگان" },
            { support: "اورجینال" },
          ],
          carType: "suv",
          gasoline: 80,
          price:94.00,
          capacity:6,
          image: "../assets/images/Car-10.png",
        },
        {
          id: 23,
          name: "MG ZX Excite",
          description: [
            { support: "گارانتی مادام العمر" },
            { support: "ارسال رایگان" },
            { support: "اورجینال" },
          ],
          carType: "hatchback",
          gasoline: 80,
          price:78.00,
          capacity:6,
          image: "../assets/images/Car-11.png",
        },
        {
          id: 24,
          name: "New MG ZS",
          description: [
            { support: "گارانتی مادام العمر" },
            { support: "ارسال رایگان" },
            { support: "اورجینال" },
          ],
          carType: "hatchback",
          gasoline: 80,
          price:100.00,
          capacity:6,
          image: "../assets/images/Car-12.png",
        },
  ];